[versions]
minecraft = "26.1.2"

# https://fabricmc.net/develop
neoforge = "26.1.2.84"
forgified_fabric_api = "0.155.0+26.1.2+3.4.2"
moddevgradle = "2.0.142"

# https://github.com/Bawnorton/MixinSquared/releases
mixinsquared = "0.3.3"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
forgified_fabric_api = { module = "org.sinytra.forgified-fabric-api:forgified-fabric-api", version.ref = "forgified_fabric_api" }

[plugins]
moddevgradle = { id = "net.neoforged.moddev", version.ref = "moddevgradle" }